# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68a5084b5d201481c7771cfdf6fa788adc88f89680451e18d2a6ccd66460e5af11d9305e46311f3dc45f5a8fdea08176cb5080a9709a53c6926a3c6540788623

test:
  secret_key_base: ff0125f0fa694dbd1a2563e82637e61037a349cdbf18ce1ec7fb1df309787cccf0a5ee22e8cbb9ae80f23459da5f334d888ed8e54d2e6a5666db23ed82fba41c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
